name: Linter And Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: .github/actions/setup.yml
      - name: Run linter
        run: poe lint
      - name: Run tests
        run: poe test
